### ISSUE TITLE
HTML-only page downloads modules imported in +onRenderClient in the browser

### ISSUE THREAD

**Issue by nitedani** [vikejs/vike#1379] opened 2023-12-24 08:08 UTC
### Description
The HTML-only page downloads all imports in +onRenderClient. (React and lodash in the reproduction)
Reproduction:
https://stackblitz.com/github/nitedani/vike-bug-html234?file=pages%2Findex%2F%2BPage.jsx

The example says:
```
<p>This page has zero browser-side JavaScript. (In development, Vite's HMR client is loaded.)</p>
```

Expected:
Only the Vike runtime is downloaded

**Comment by nitedani** [comment] 2023-12-24 21:25
Using this page config solves the issue. React and lodash are no longer downloaded. The built page entry will become an empty .js file, and the empty file is downloaded.:
```
export default {
  clientRouting: false,
  meta: {
    Page: {
      env: {
        server: true,
        client: false,
      },
    },
    onRenderClient: {
      env: { client: false }, <---
    }
  }
} satisfies Config
```


This config doesn't work as expected. `onRenderClient` is bundled and downloaded, but not called on the client.:
```
export default {
  clientRouting: false,
  meta: {
    Page: {
      env: {
        server: true,
        client: false,
      },
    },
    onRenderClient: {
      env: { client: true }, <---
    }
  }
} satisfies Config
```


Questions:
Why is `onRenderClient` not called using the config above?
What is the expected default behavior for the following config? Currently, it behaves the same like the config above. It bundles onRenderClient, even though it's not called in the browser.

```
export default {
  clientRouting: false,
  meta: {
    Page: {
      env: {
        server: true,
        client: false,
      },
    }
  }
} satisfies Config
```

**Comment by brillout** [comment] 2023-12-25 10:14
The issue was a regression that added preload tags to HTML-only pages which doesn't make sense since no script is exectued. It's fixed now and I added tests to the CI.

> Ideas

I agree Vike could be smarter / more flexible. Although I think the fix is fine as I don't foresee a use case that'd need Vike to be more clever around this. Closing but feel free to disagree.

**Closed by brillout** 2023-12-25 10:14 UTC
Labels: bug :boom:
