### ISSUE TITLE
Cannot build project

### ISSUE THREAD

**Issue by EugenPrinz** [vikejs/vike#1887] opened 2024-09-21 16:12 UTC
### Description

I created a test project through `npm create bati mainframe-ssrv2 -- --react --authjs --express --prisma --eslint --prettier` and I can’t build it, I don’t understand why the config file is blocked.

`npm run dev` - Works intermittently
`npm cache verify` - It doesn't always help

<pre>
error during build:
Error: EBUSY: resource busy or locked, unlink 'C:\Workspace\Webstorm\mainframe-ssrv2\pages\todo\+config.ts.build-47bf93auo05g.mjs'
    at Object.unlinkSync (node:fs:1876:11)
    at clean (file:///C:/Workspace/Webstorm/mainframe-ssrv2/node_modules/vike/dist/esm/node/plugin/plugins/importUserCode/v1-design/getVikeConfig/transpileAnd
ExecuteFile.js:238:28)
    at executeTranspiledFile (file:///C:/Workspace/Webstorm/mainframe-ssrv2/node_modules/vike/dist/esm/node/plugin/plugins/importUserCode/v1-design/getVikeCon
fig/transpileAndExecuteFile.js:244:9)
    at transpileAndExecuteFile (file:///C:/Workspace/Webstorm/mainframe-ssrv2/node_modules/vike/dist/esm/node/plugin/plugins/importUserCode/v1-design/getVikeC
onfig/transpileAndExecuteFile.js:33:29)
    at loadConfigFile (file:///C:/Workspace/Webstorm/mainframe-ssrv2/node_modules/vike/dist/esm/node/plugin/plugins/importUserCode/v1-design/getVikeConfig/loa
dFileAtConfigTime.js:37:29)
    at file:///C:/Workspace/Webstorm/mainframe-ssrv2/node_modules/vike/dist/esm/node/plugin/plugins/importUserCode/v1-design/getVikeConfig.js:101:52
    at async Promise.all (index 1)
    at loadInterfaceFiles (file:///C:/Workspace/Webstorm/mainframe-ssrv2/node_modules/vike/dist/esm/node/plugin/plugins/importUserCode/v1-design/getVikeConfig
.js:96:5)
    at loadVikeConfig (file:///C:/Workspace/Webstorm/mainframe-ssrv2/node_modules/vike/dist/esm/node/plugin/plugins/importUserCode/v1-design/getVikeConfig.js:
236:40)
    at loadVikeConfig_withErrorHandling (file:///C:/Workspace/Webstorm/mainframe-ssrv2/node_modules/vike/dist/esm/node/plugin/plugins/importUserCode/v1-design
/getVikeConfig.js:198:15)
</pre>

**Comment by brillout** [comment] 2024-09-21 22:42
I cannot reproduce. It seems to be some kind of Windows quirk that is unrelated to Vike? Is there anything Vike can do to workaround it? Closing, but let's continue the conversation.

**Closed by brillout** 2024-09-21 22:42 UTC
Labels: bug :boom:

**Comment by EugenPrinz** [comment] 2024-09-22 00:15
> I cannot reproduce. It seems to be some kind of Windows quirk that is unrelated to Vike? Is there anything Vike can do to workaround it? Closing, but let's continue the conversation.

Maybe something happened when reinstalling the operating system, I had to set a delay of 1 millisecond in the executeTranspiledFile method, after which the build completed successfully.

Sorry for disturbing you.

**Comment by brillout** [comment] 2024-09-22 10:02
> the problem was in the webstorm plugin

Good to know, can you elaborate or link to a relevant resource?
