### ISSUE TITLE
assertWarning stack trace wrong Line & Column in user code

### ISSUE THREAD

**Issue by upupming** [vikejs/vike#1355] opened 2023-12-14 05:37 UTC
### Description

See repro of https://github.com/upupming/vike/tree/warning-loc.

```
cd examples/react-full-v1
pnpm dev

➜  react-full-v1 git:(main) ✗ pnpm dev

> @ dev /Users/upupming/projects/vike/examples/react-full-v1
> vite

  VITE v4.5.1  ready in 1195 ms
  ➜  Local:   http://localhost:3000/
  ➜  Network: use --host to expose
  ➜  press h to show help
1:22:40 PM [vike][request(1)] HTTP request: /
1:22:40 PM [vike][request(1)][Warning] `pageContext.url` is outdated. Use `pageContext.urlPathname`, `pageContext.urlParsed`, or `pageContext.urlOriginal` instead. (See https://vike.dev/migration/0.4.23 for more information.)
    at assertWarning (file:///Users/upupming/projects/vike/vike/dist/esm/utils/assert.js:94:21)
    at Object.urlGetter (file:///Users/upupming/projects/vike/vike/dist/esm/shared/addUrlComputedProps.js:65:5)
    at route (/Users/upupming/projects/vike/examples/react-full-v1/pages/hello/+route.ts:10:38)
    at resolveRouteFunction (file:///Users/upupming/projects/vike/vike/dist/esm/shared/route/resolveRouteFunction.js:10:18)
    at file:///Users/upupming/projects/vike/vike/dist/esm/shared/route/index.js:74:33
    at Array.map (<anonymous>)
    at route (file:///Users/upupming/projects/vike/vike/dist/esm/shared/route/index.js:43:47)
    at renderPageNominal (file:///Users/upupming/projects/vike/vike/dist/esm/node/runtime/renderPage.js:243:38)
    at renderPageAlreadyPrepared (file:///Users/upupming/projects/vike/vike/dist/esm/node/runtime/renderPage.js:113:45)
    at renderPageAndPrepare (file:///Users/upupming/projects/vike/vike/dist/esm/node/runtime/renderPage.js:93:12)
route /
1:22:41 PM [vike][request(1)] HTTP response / 200
```

<img width="1037" alt="image" src="https://github.com/vikejs/vike/assets/24741764/bfb0494f-b8a2-446c-84ff-8c1abd9ac4fe">

The reported Line&Column number is not correct in the source code.

I have also tried `+route.js` file, the line info is also wrong:

<img width="1536" alt="image" src="https://github.com/vikejs/vike/assets/24741764/e1d6e769-1e3c-4c89-a04f-5584be6583b7">

**Comment by brillout** [comment] 2023-12-14 08:38
Thanks for the reproduction. Since it isn't a blocker, I will have a look at this later next week.

**Comment by brillout** [comment] 2024-01-02 20:13
Indeed I can reproduce, let me dig into it.

**Comment by brillout** [comment] 2024-01-02 21:10
I can reproduce without Vike, so it seems to be a Vite issue. Closing this in favor of https://github.com/vitejs/vite/issues/15490.

I also doubled checked all Vike transformers and I don't see how any of them can break source maps.

**Closed by brillout** 2024-01-02 21:10 UTC
Labels: bug :boom:, not-a-blocker

**Comment by brillout** [comment] 2024-01-05 22:19
Actually, it was a Vike issue after all. It's now fixed.

That said, I still can reproduce some Vite issues around source maps (I've updated the repro linked at https://github.com/vitejs/vite/issues/15490), so there may be some issues left.
