### ISSUE TITLE
Change Pages to pages but, FileSystem Route is not working.

### ISSUE THREAD

**Issue by N-Joy-Shadow** [vikejs/vike#1550] opened 2024-03-12 17:05 UTC
### Description

I'm migrating from vite-react to vike.

Originally, I was using react-router-dom and storing react files in a folder called Pages. However, during the process of migrating to vike, I realized that Pages doesn't work, so I changed the folder name to pages, but Route is catching it as /Pages, and even if I go into /Pages, it's not working correctly.

+conifg.ts
```ts
import type { Config } from 'vike/types'
import vikeReact from 'vike-react/config'

export default {
    title : "title",
    ssr : true,
    extends : vikeReact,
} satisfies Config
```
+Page.tsx
```tsx
function Page() {
    return (
        <>
            <h1>hi</h1>
        </>
    )
}

export default Page
```
log
![image](https://github.com/vikejs/vike/assets/57449485/4748168e-617c-40fa-8a60-30ca1f43a639)

![image](https://github.com/vikejs/vike/assets/57449485/59a38f03-5893-4f9d-b765-450d5cfce163)

I've checked it works in a new project, and the FileSystem Route using pages in the top-level folder works fine.

**Comment by brillout** [comment] 2024-03-12 17:10
Hm, I can't tell whether it's a user land issue or a Vike issue. The error is  quiteunexpected though. If you can reliably reproduce that error and publish a reproduction that'd great. Closing but I'll re-open if I can get my hands on a reproduction, looking forward to it.

**Closed by brillout** 2024-03-12 17:10 UTC
Labels: bug :boom:

**Comment by N-Joy-Shadow** [comment] 2024-03-12 17:31
I think I found the solution.
I deleted the .git folder, and the Pages for it now appears as pages.
I think it's because git is tracking Pages.
![vike_git_issue](https://github.com/vikejs/vike/assets/57449485/4ad5ac52-7dbe-42c7-bc4a-36acfd84b4e0)

**Comment by brillout** [comment] 2024-03-12 17:47
Hm, I couldn't reproduce any error by removing `.git`.

**Comment by N-Joy-Shadow** [comment] 2024-03-12 18:22
I've tried to reproduce it in a new project and it doesn't work either.

In the original code, replacing pages with pages in webstorm or vsc was an error.
The error looked like this
![image](https://github.com/vikejs/vike/assets/57449485/5e70f9c1-59d1-4203-b17a-25513799c9aa)
![image](https://github.com/vikejs/vike/assets/57449485/080574ba-99e9-4cda-8b87-3393e1d37bc5)
