### ISSUE TITLE
Build fails when prerendering pages with catch-all route strings configured

### ISSUE THREAD

**Issue by andriygm** [vikejs/vike#1529] opened 2024-02-28 21:19 UTC
### Description

When pre-rendering is set to partial, the page should still render instead of causing the entire build to fail -- it should either fall back to pre-rendering the filesystem route or some other fallback. (this issue is partially related to #1476 WRT allowing framework client-side router to take over under catch-all routes)

### Reproduction
https://stackblitz.com/edit/vcirhv

**Comment by brillout** [comment] 2024-02-29 09:00
How is that not a duplicate of #1476?

> https://stackblitz.com/edit/vcirhv

What are the reproduction steps?

> build to fail 

What is the thrown error?

Closing, but I'll re-open after we get to some more clarity.

**Closed by brillout** 2024-02-29 09:00 UTC
Labels: bug :boom:

**Comment by andriygm** [comment] 2024-02-29 15:26
>How is that not a duplicate of https://github.com/vikejs/vike/issues/1476?

I suppose it's a subset of #1476 -- this issue is more so referring to the fact that pre-render flat out fails -- IMO the build should at least fall back to its filesystem route and throw a warning reference the limitation present in #1476. 

>What are the reproduction steps?

Whoops, the stackblitz link is missing the prerender: partial config, see below for correct reproduction

1. Start with Bati Solid project
2. Add catch-all to pages/index/ folder under +route.ts
3. Add prerender: {partial: true} to vite.config.ts under vike plugin
4. `pnpm run build`

>What is the thrown error?

```Error: [vike@0.4.164][Bug] You stumbled upon a Vike bug. Go to https://github.com/vikejs/vike/issues/new and copy-paste this error. A maintainer will fix the bug (usually under 24 hours).
    at Module.getUrlFromRouteString (/home/projects/vcirhv/node_modules/.pnpm/vike@0.4.164_vite@5.1.4/node_modules/vike/dist/esm/shared/route/resolveRouteString.js:131:17)
    at eval (/home/projects/vcirhv/node_modules/.pnpm/vike@0.4.164_vite@5.1.4/node_modules/vike/dist/esm/node/prerender/runPrerender.js:282:61)
    at eval (/home/projects/vcirhv/node_modules/.pnpm/vike@0.4.164_vite@5.1.4/node_modules/vike/dist/esm/utils/pLimit.js:44:37)
    at run (/home/projects/vcirhv/node_modules/.pnpm/vike@0.4.164_vite@5.1.4/node_modules/vike/dist/esm/utils/pLimit.js:44:49)
    at eval (/home/projects/vcirhv/node_modules/.pnpm/vike@0.4.164_vite@5.1.4/node_modules/vike/dist/esm/utils/pLimit.js:62:32)```

**Comment by brillout** [comment] 2024-03-01 18:21
Agreed & done.
