### ISSUE TITLE
 Potential Bug: Upgrade to Vike 0.4.172 Breaks HMR in Dev Mode

### ISSUE THREAD

**Issue by CookedApps** [vikejs/vike#1725] opened 2024-07-02 08:34 UTC
### Issue Summary
After upgrading from Vike version 0.4.171 to 0.4.177, our app breaks in development mode when running `vite`. The error does not occur when building and serving the app. We identified that the issue originates from the upgrade from Vike version 0.4.171 to 0.4.172.

### Steps to Reproduce
1. Upgrade Vike from 0.4.171 to 0.4.172
2. Run the app in development mode using `vite`
3. Observe the error in the browser console

### Observed Error
```
[vite] connecting...
LocationPayloadProvider.tsx:1 Uncaught Error: @vitejs/plugin-react can't detect preamble. Something is wrong. See https://github.com/vitejs/vite-plugin-react/pull/11#discussion_r430879201
    at LocationPayloadProvider.tsx:1:52
[vite] connected.
```

### Additional Context
- The error is not specific to `LocationPayloadProvider.tsx` and occurs with other components if this component is removed.
- Clearing `node_modules` and reinstalling dependencies does not resolve the issue.
- Upgrading to the newest Vike version (0.4.177) did not resolve the issue.

### Project Context
- **Vike:** 0.4.172 (also tested 0.4.177 and everything in between)
- **Vite:** 5.3.2
- **@vitejs/plugin-react:** 4.3.1
- **TypeScript:** 5.5.3
- **Node:** 20.9.0
- **pnpm:** 9.1.0

### `vite.config.ts` Plugins Section
```typescript
import ReactPlugin from '@vitejs/plugin-react'
import VikePlugin from 'vike/plugin'
...

plugins: [
  VikePlugin({
    prerender: true,
  }),
  ReactPlugin({
    babel: {
      plugins: [
        ['macros'],
        ['@babel/plugin-proposal-decorators', { legacy: true }],
        ['@babel/plugin-transform-class-properties'],
      ],
    },
  }),
  LinguiPlugin(),
  LinguiDictionariesPlugin(),
  ViteSvgrPlugin(),
  SitemapPlugin(),
  SassDtsPlugin({
    enabledMode: ['development', 'production'],
    sourceDir: path.resolve(__dirname, './src'),
  }),
],
```

### Request for Assistance
We are unsure how to resolve this issue and would appreciate any help or hints. Thank you! 🙏

**Comment by brillout** [comment] 2024-07-02 08:40
> @vitejs/plugin-react can't detect preamble.

This error doesn't come from Vike, and I don't see how HMR preamble issues could be related to Vike.

I'm inclined to think it's unrelated to Vike, thus closing. But minimal reproduction welcome with minmal diffs to a Bati app or Vike example.

**Closed by brillout** 2024-07-02 08:41 UTC
Labels: bug :boom:

**Comment by CookedApps** [comment] 2024-07-02 08:42
@brillout 
> > @vitejs/plugin-react can't detect preamble.
> 
> This error doesn't come from Vike, and I don't see how HMR preamble issues could be related to Vike.
> 
> I'm inclined to think it's unrelated to Vike, thus closing. But minimal reproduction welcome with minmal diffs to a Bati app or Vike example.

We only updated Vike and didn't touch anything else. Why do you think it's unrelated to Vike?

**Comment by brillout** [comment] 2024-07-02 08:45
I think a minimal reproduction would be the best here.

**Comment by pinge** [comment] 2024-07-16 23:05
Hi @brillout, thanks a lot for your hard work on Vike, amazing framework! 🙇 

We're using Prerender/SSG with React and we've just stumbled upon this same issue when running Vite for local development (e.g. `yarn vite`). Although the project is a bit large to easily provide a reproducible example, I believe I've narrowed down the issue that @CookedApps is mentioning.

[This commit](https://github.com/vikejs/vike/commit/a3be1984ab8d80bff5a4048aeef18b3275334d94#diff-02fe6c7bb0427d3c2dfde489bd8c350f3c4196a091f1e15fd647f0133f462ad1R26) seems to be the culprit, where the parentheses around `import` statements/operators in the `mergeScriptTags` function have been removed:

```
contents.push(`import ${JSON.stringify(src)};`)
````

Removing the parentheses changes the `import()` [dynamic operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import) to an `import` [statement](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import), which won't work for local files being served using HMR:

```html
<script type="module" async="">
  import RefreshRuntime from "/@react-refresh"
  RefreshRuntime.injectIntoGlobalHook(window)
  window.$RefreshReg$ = () => {}
  window.$RefreshSig$ = () => (type) => type
  window.__vite_plugin_react_preamble_installed__ = true
  import "/@vite/client";
  import "/@fs/.../your_vike_project/node_modules/vike/dist/esm/client/client-routing-runtime/entry.js";
</script>
```

The syntax error prevents the HMR preamble code to be executed on the client side.

So far I've been able to fix it by patching Vike versions `>= 0.4.172`, but it would be nice to fix this if my findings make sense to you. I wouldn't mind contributing if you believe the scope is limited to `mergeScriptTags()` and its test coverage.

**Comment by brillout** [comment] 2024-07-17 06:29
@pinge Thank you for reaching out!

> The syntax error prevents the HMR preamble code to be executed on the client side.

Can you elaborate on that? It would be nice if we can fix the issue while keeping static imports.

**Comment by pinge** [comment] 2024-07-17 15:18
I'll try, to my best understanding:

It looks like there is an issue when using a static import with a virtual module (`importUserCode` plugin). We do have custom client routing code, so I'm not sure whether that is breaking the static import or not.

Spent a bit more time digging into it and it looks like the static import fails when executing the following statement in [`dist/esm/client/client-routing-runtime/pageFiles.js`](https://github.com/vikejs/vike/blob/main/vike/client/client-routing-runtime/pageFiles.ts#L3C1-L3C86):

```typescript
import * as pageFilesExports from 'virtual:vike:importUserCode:client:client-routing'
```

 I haven't read through all Vike's codebase, but what comes to mind is if the parent module (`entry.js`) can be statically imported when it includes a virtual module.

Besides coming up with a small reproducible demo, do you have any ideas on how I can debug this further?

**Comment by brillout** [comment] 2024-07-17 15:54
I can't say, but so far I don't see how virtual modules can be related.

> how I can debug this further?

I would dig on Vite's side. Vite has some HMR debug logs, and I'd inject some `console.log()` at `node_modules/vite/`. In my experience, it quickly leads to a lot of insights (also interesting to see how Vite's HMR works).

**Comment by peterlacko** [comment] 2024-10-11 12:48
@CookedApps did you solve the issue? I'm also facing it, thanks!

**Comment by CookedApps** [comment] 2024-10-11 18:44
> @CookedApps did you solve the issue? I'm also facing it, thanks!

@peterlacko 

It was indeed Vike breaking the injection of the HMR preamble. So our workaround was to inject the preamble manually in our `+onRenderHtml` like so: 
```tsx
export const onRenderHtml: OnRenderHtmlAsync = async (pageContext): ReturnType<OnRenderHtmlAsync> => {
  // stuff ...

  // Generate the preamble
  const hmrPreamble = perpareFastRefreshPreamble()

  const documentHtml = escapeInject`
    <!DOCTYPE html>
    <html lang="${lang}" dir="auto">
      <!-- your stuff ... -->
      
      <!-- Inject the preamble here: -->
      ${hmrPreamble}
    </html>
  `
  return { documentHtml, pageContext: {} }
}


function perpareFastRefreshPreamble() {
  // Skip preamble if not dev mode
  if (!import.meta.env.DEV) return ''

  // This is a workaround for the issue that React Fast Refresh doesn't work in Vite dev mode
  // after upgrading to Vike 0.4.172. It should be removed when the issue is fixed.
  return escapeInject`
    <script type="module">
      import RefreshRuntime from "/@react-refresh"
      RefreshRuntime.injectIntoGlobalHook(window)
      window.$RefreshReg$ = () => {}
      window.$RefreshSig$ = () => (type) => type
      window.__vite_plugin_react_preamble_installed__ = true
    </script>
  `
}
```

If this issue is being resolved by a newer Vike version (or Vite or what ever is causing this), we would just remove this manual injection.

**Comment by brillout** [comment] 2024-10-11 19:09
If someone can provide a minimal reproduction, I'll look at whether the issue is caused by Vike and whether Vike can fix/workaround the issue.
