### ISSUE TITLE
Vike Bug during SSR generation

### ISSUE THREAD

**Issue by Meulitz** [vikejs/vike#1597] opened 2024-04-04 08:48 UTC
### Description

We got an issue in our lampda function after updating vike to version  `0.4.168`

```
"error": {
    "Error": "Error",
    "Cause": "{\"errorType\":\"Error\",\"errorMessage\":\"Could not build SSR HTML file: Error: [@brillout/vite-plugin-server-entry@0.4.5][Bug] You stumbled upon a bug in the source code of @brillout/vite-plugin-server-entry. Reach out at https://github.com/brillout/vite-plugin-server-entry/issues/new and include this error stack (the error stack is usually enough to fix the problem). A maintainer will fix the bug (usually under 24 hours). Don't hesitate to reach out as it makes @brillout/vite-plugin-server-entry more robust.\",\"trace\":[\"Error: Could not build SSR HTML file: Error: [@brillout/vite-plugin-server-entry@0.4.5][Bug] You stumbled upon a bug in the source code of @brillout/vite-plugin-server-entry. Reach out at https://github.com/brillout/vite-plugin-server-entry/issues/new and include this error stack (the error stack is usually enough to fix the problem). A maintainer will fix the bug (usually under 24 hours). Don't hesitate to reach out as it makes @brillout/vite-plugin-server-entry more robust.\",\"    at Runtime.handler (file:///var/task/lambda.js:120:11)\"]}"
```

**Comment by brillout** [comment] 2024-04-04 08:51
What is the content of `file:///var/task/lambda.js:120:11`? You should see an `assert()` line.

**Comment by Meulitz** [comment] 2024-04-04 08:55
```
    throw new Error(`Could not build SSR HTML file: ${errorWhileRendering}`);
``` 

this is what I can see in our code at this position

**Comment by brillout** [comment] 2024-04-04 08:57
Look at `errorWhileRendering.stack`.

**Comment by Meulitz** [comment] 2024-04-04 09:18
```
Cause": "{\"errorType\":\"Error\",\"errorMessage\":\"Could not build SSR HTML file: Error: [@brillout/vite-plugin-server-entry@0.4.5][Bug] You stumbled upon a bug in the source code of @brillout/vite-plugin-server-entry. Reach out at https://github.com/brillout/vite-plugin-server-entry/issues/new and include this error stack (the error stack is usually enough to fix the problem). A maintainer will fix the bug (usually under 24 hours). Don't hesitate to reach out as it makes @brillout/vite-plugin-server-entry more robust.\\n    at crawlServerEntryFileWithNodeJs (/var/task/node_modules/@brillout/vite-plugin-server-entry/dist/importServerEntry/index.js:131:24)\\n    at async importServerEntry (/var/task/node_modules/@brillout/vite-plugin-server-entry/dist/importServerEntry/index.js:46:19)\\n    at async loadImportBuild (file:///var/task/node_modules/vike/dist/esm/node/runtime/globalContext/loadImportBuild.js:13:9)\\n    at async initGlobalContext (file:///var/task/node_modules/vike/dist/esm/node/runtime/globalContext.js:109:30)\\n    at async renderPageAndPrepare (file:///var/task/node_modules/vike/dist/esm/node/runtime/renderPage.js:64:9)\\n    at async renderPage_wrapper (file:///var/task/node_modules/vike/dist/esm/node/runtime/renderPage.js:26:24)\\n    at async renderPage (file:///var/task/node_modules/vike/dist/esm/node/runtime/renderPage.js:45:35)\\n    at async Runtime.handler (file:///var/task/lambda.js:108:63)\",\"trace\":[\"Error: Could not build SSR HTML file: Error: [@brillout/vite-plugin-server-entry@0.4.5][Bug] You stumbled upon a bug in the source code of @brillout/vite-plugin-server-entry. Reach out at https://github.com/brillout/vite-plugin-server-entry/issues/new and include this error stack (the error stack is usually enough to fix the problem). A maintainer will fix the bug (usually under 24 hours). Don't hesitate to reach out as it makes @brillout/vite-plugin-server-entry more robust.\",\"    at crawlServerEntryFileWithNodeJs (/var/task/node_modules/@brillout/vite-plugin-server-entry/dist/importServerEntry/index.js:131:24)\",\"    at async importServerEntry (/var/task/node_modules/@brillout/vite-plugin-server-entry/dist/importServerEntry/index.js:46:19)\",\"    at async loadImportBuild (file:///var/task/node_modules/vike/dist/esm/node/runtime/globalContext/loadImportBuild.js:13:9)\",\"    at async initGlobalContext (file:///var/task/node_modules/vike/dist/esm/node/runtime/globalContext.js:109:30)\",\"    at async renderPageAndPrepare (file:///var/task/node_modules/vike/dist/esm/node/runtime/renderPage.js:64:9)\",\"    at async renderPage_wrapper (file:///var/task/node_modules/vike/dist/esm/node/runtime/renderPage.js:26:24)\",\"    at async renderPage (file:///var/task/node_modules/vike/dist/esm/node/runtime/renderPage.js:45:35)\",\"    at async Runtime.handler (file:///var/task/lambda.js:108:63)\",\"    at Runtime.handler (file:///var/task/lambda.js:120:11)\"]}"
```

**Comment by brillout** [comment] 2024-04-04 09:22
Hm, that's unexpected and doesn't seem to be a regression on our part. What's the content of `$ ls dist/server/`?

**Comment by Meulitz** [comment] 2024-04-04 09:48
![image](https://github.com/vikejs/vike/assets/129262066/41e6014b-a50e-49ad-9c48-c94e4a7f1ef4)

**Comment by brillout** [comment] 2024-04-04 09:51
As you can see in `/var/task/node_modules/@brillout/vite-plugin-server-entry/dist/importServerEntry/index.js:131:24`, the `dist/server/entry.{js,mjs,cjs}` file is expected to exist but it doesn't. Why doesn't it exist? Do you remove it? Do you use a Vite plugin that removes it?

Make sure you really do use Vike's latest version.

**Comment by Meulitz** [comment] 2024-04-04 10:10
we using the version `0.4.168` we only figured out this issue after the update.
At which state this entry is created should we can do anything to debug why it is missing?

**Comment by brillout** [comment] 2024-04-04 10:13
It seems to be a user land issue, not a Vike issue. So I don't know nor can I guess why it's being removed.

If you can provide a minimal reproduction then I'll be able to have a look at it.

**Comment by brillout** [comment] 2024-04-05 08:02
Closing but let's continue the conversation. I'll re-open if I can get my hands on a reproduction, or if I can get more information about this.

@Meulitz Keep us updated.

**Closed by brillout** 2024-04-05 08:02 UTC
Labels: bug :boom:
