### ISSUE TITLE
Vike Bug during vitest run

### ISSUE THREAD

**Issue by mpiniarski** [vikejs/vike#1591] opened 2024-04-02 08:59 UTC
### Description

Hello, when running `vitest run` I get the following error:
```
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Error ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
Error: [vike@0.4.167][Bug] You stumbled upon a Vike bug. Go to https://github.com/vikejs/vike/issues/new and copy-paste this error. A maintainer will fix the bug (usually under 24 hours).
    at assertIsNpmPackageImport (file:///Users/mpiniarski/Projects/Siemens/frontend-core/node_modules/vike/dist/esm/utils/isNpmPackage.js:22:5)
    at file:///Users/mpiniarski/Projects/Siemens/frontend-core/node_modules/vike/dist/esm/node/plugin/plugins/devConfig/determineOptimizeDeps.js:55:21
    at Array.forEach (<anonymous>)
    at file:///Users/mpiniarski/Projects/Siemens/frontend-core/node_modules/vike/dist/esm/node/plugin/plugins/devConfig/determineOptimizeDeps.js:38:59
    at Array.forEach (<anonymous>)
    at getPageDeps (file:///Users/mpiniarski/Projects/Siemens/frontend-core/node_modules/vike/dist/esm/node/plugin/plugins/devConfig/determineOptimizeDeps.js:37:21)
    at determineOptimizeDeps (file:///Users/mpiniarski/Projects/Siemens/frontend-core/node_modules/vike/dist/esm/node/plugin/plugins/devConfig/determineOptimizeDeps.js:12:40)
    at configResolved (file:///Users/mpiniarski/Projects/Siemens/frontend-core/node_modules/vike/dist/esm/node/plugin/plugins/devConfig/index.js:57:17)
    at async Promise.all (index 7)
    at resolveConfig (file:///Users/mpiniarski/Projects/Siemens/frontend-core/node_modules/vitest/node_modules/vite/dist/node/chunks/dep-C-KAszbv.js:68253:5)
    at _createServer (file:///Users/mpiniarski/Projects/Siemens/frontend-core/node_modules/vitest/node_modules/vite/dist/node/chunks/dep-C-KAszbv.js:64503:20)
    at createViteServer (file:///Users/mpiniarski/Projects/Siemens/frontend-core/node_modules/vitest/dist/vendor/cac.RvTIWZBK.js:10951:18)
    at createVitest (file:///Users/mpiniarski/Projects/Siemens/frontend-core/node_modules/vitest/dist/vendor/cac.RvTIWZBK.js:12219:18)
    at startVitest (file:///Users/mpiniarski/Projects/Siemens/frontend-core/node_modules/vitest/dist/vendor/cac.RvTIWZBK.js:18772:15)
    at start (file:///Users/mpiniarski/Projects/Siemens/frontend-core/node_modules/vitest/dist/vendor/cac.RvTIWZBK.js:19563:17)
    at CAC.run (file:///Users/mpiniarski/Projects/Siemens/frontend-core/node_modules/vitest/dist/vendor/cac.RvTIWZBK.js:19544:3)

```

i'm using `"vike": "0.4.167"`, `"vite": "4.4.0"` and ` "vitest": "0.32.0"` (but the error also happens with `"vitest": "1.4.0"`)

**Comment by brillout** [comment] 2024-04-02 12:56
Do you get this with `0.4.168` as well? If yes, then share the new stack trace for that version.

Closing in the meantime, but I'll re-open if you still get this with 168.

**Closed by brillout** 2024-04-02 12:56 UTC
Labels: bug :boom:

**Comment by mpiniarski** [comment] 2024-04-02 13:02
`0.4.168` fixes the issue, thanks

**Comment by brillout** [comment] 2024-04-02 13:04
Ok great. (Btw. in case your company would be for it: https://github.com/vikejs/vike/issues/1350, it makes a massive difference.)

**Comment by vchirikov** [comment] 2024-04-02 23:24
@brillout Hi, I found that this can also be caused by the full path in `--root` vitest's parameter on Windows

Should the issue be reopened?

![image](https://github.com/vikejs/vike/assets/40987940/ea5b349b-8b23-4392-bc17-8a09001a637e)

```js
    "vike": "0.4.168",
    "vite": "5.2.7",
    "vitest": "1.4.0"
```

**Comment by brillout** [comment] 2024-04-03 05:47
I presume this one can also be reproduced on Linux / MacOS?
