### ISSUE TITLE
Option to externalise pageContext payload to a file

### ISSUE THREAD

**Issue by spacedawwwg** [vikejs/vike#421] opened 2022-08-16 18:22 UTC
### Description

As the payload is only needed for hydration, it would be nice to have the option to externalise pageContext to file rather than increase the HTML payload directly with the inline script.

Utilising a service worker would allow caching the external payload while continuing to work with a "network first" approach for the HTML, so if the script hash changes the new payload would be requested.

It would also benefit non Javascript users by not needing to download the unnecessary payload.

**Comment by brillout** [comment] 2022-08-17 09:02
While I share the sentiment here, I don't see a way to implement this.

The problem is that the `pageContext` passed to the browser needs to be exactly the same than the `pageContext` that was used to render the HTML.

There is no clear way how to do that with your proposal.

**Comment by spacedawwwg** [comment] 2022-08-19 14:20
my suggestion is that the inline json is externalised into a file.

`<script id="vite-plugin-ssr_pageContext" src="/my-page/payload.js"></script>`

```javascript
// /my-page/payload.js

window.pageContextJson = {
  "pageContext": {
    "_pageId": "/src/pages/UcoHome/UcoHome",
    "pageProps": {
      ...
    }
  }
};
```

```javascript
// getPageContextSerializedInHtml.ts 

const pageContextJson = window.pageContextJson || document.getElementById('vite-plugin-ssr_pageContext')?.textContent
```

**Comment by brillout** [comment] 2022-08-19 18:51
Yea, that's what I understood to be what you want. But I don't think it's possible.

Because it's a single `pageContext` object shared between two HTTP requests. You can imagine how problematic that is. (E.g. the server would need to keep the `pageContext` object around, waiting until the second HTTP request comes in.)

**Comment by spacedawwwg** [comment] 2022-08-19 21:36
I'm probably missing something, but the suggestion is the same way Nuxt.js does it

**Comment by brillout** [comment] 2022-08-20 07:11
I guess it only does it for pre-rendered websites?

For pre-rendered websites it's possible and actually vps already generates a static `.pageContext.json` for each page.

**Comment by spacedawwwg** [comment] 2022-08-24 11:20
![image](https://user-images.githubusercontent.com/1691867/186405899-ff49f41d-e049-463c-8e3a-e8ac4643b76b.png)

looks that way, yeah

**Comment by brillout** [comment] 2022-08-24 17:18
Leaving this ticket open for implementing your suggestion for fully pre-rendered websites (aka SSG).

I think it's low priority though. (Feel free to disagree with the priority.)

**Comment by brillout** [comment] 2023-11-16 20:58
Closing because it's low priority. I'm more than open to re-open if it's a blocker for someone.

**Closed by brillout** 2023-11-16 20:58 UTC
Labels: enhancement :sparkles:
